---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: app01
  namespace: app01
  labels:
    app.kubernetes.io/name: httpbin
    app.kubernetes.io/instance: app01
spec:
  hostnames:
    - 'localhost'
    - '127.0.0.1'
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
      port: 80
  rules:
    # Route /app01/* to httpbin backend with path rewriting
    - matches:
        - path:
            type: PathPrefix
            value: /app01
      backendRefs:
        - name: httpbin
          port: 80
          weight: 100
      filters:
        # Strip /app01 prefix before forwarding to backend
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
