apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: vm-system
spec:
  type: default
  interval: 30m
  url: https://victoriametrics.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: vm-system
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.63.5
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: vm-system
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: vm-k8s-stack-values
      valuesKey: values.yaml
