checks:
  # Disable checks that might not be relevant for your setup
  doNotAutoAddDefaults: false
  # Add specific checks to exclude if needed
  exclude:
    - "latest-tag"
    # Uncomment to exclude specific checks
    # - "no-read-only-root-fs"
    # - "run-as-non-root"
# Include only specific checks (comment out to use defaults)
# include:
#   - "required-label-owner"
#   - "required-label-app"

customChecks: []
# Exclude paths from scanning
exclude:
  - "node_modules/**"
  - ".git/**"
  - "scripts/**"
