# Prettier configuration for YAML formatting

# Print width
printWidth: 100

# Use 2 spaces for indentation (K8s standard)
tabWidth: 2

# Use spaces instead of tabs
useTabs: false

# No semicolons (not applicable for YAML)
semi: false

# Use single quotes
singleQuote: true

# Add trailing commas where valid in ES5 (not applicable for YAML)
trailingComma: 'none'

# Print spaces between brackets
bracketSpacing: true

# Put the > of a multi-line element on the next line
bracketSameLine: false

# Maintain existing line breaks
proseWrap: 'preserve'

# Ensure files end with newline
endOfLine: 'lf'

# Override for YAML files specifically
overrides:
  - files: '*.yaml'
    options:
      printWidth: 100
      tabWidth: 2
  - files: '*.yml'
    options:
      printWidth: 100
      tabWidth: 2
