# yamllint configuration for Kubernetes and Helm projects
# Relaxed rules suitable for K8s manifests and Helm templates

extends: default

rules:
  # Line length - relaxed for long Kubernetes resource names/labels
  line-length:
    max: 120
    level: warning

  # Indentation - 2 spaces (K8s standard)
  indentation:
    spaces: 2
    indent-sequences: true

  # Allow empty values (common in K8s for optional fields)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Document start (---) is optional
  document-start: disable

  # Trailing spaces are handled by pre-commit hook
  trailing-spaces: enable

  # Comments indentation
  comments:
    min-spaces-from-content: 1

  # Truthy values - allow yes/no/on/off (common in K8s)
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Brackets - allow flexibility for inline definitions
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces - allow flexibility
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Quoted strings - allow both styles
  quoted-strings:
    quote-type: any
    required: false

  # Key duplicates are errors
  key-duplicates: enable

  # Octal values - allow for file permissions
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

ignore: |
  # ignore cluster specific files
  clusters/docker-desktop/flux-system/gotk-components.yaml
  clusters/docker-desktop/flux-system/gotk-sync.yaml
  clusters/docker-desktop/flux-system/kustomization.yaml

  # Ignore common directories
  .git/
  .github/
  node_modules/
  venv/
  __pycache__/
  *.pyc
