apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: egw-controller
  namespace: gw-system
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: gateway-helm
      version: v1.6.0
      sourceRef:
        kind: HelmRepository
        name: egw-controller
        namespace: gw-system
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values: {}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: egw-controller
  namespace: gw-system
spec:
  type: oci
  interval: 30m
  url: oci://docker.io/envoyproxy
