---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: gateway-helm
      version: v1.6.0
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy-gateway-system
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  # Ensure all CRDs are created/updated during helm operations
  crds:
    - version: v1
      kind: CustomResourceDefinition
  values:
    # Install CRDs if the chart supports it
    installCRDs: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  type: oci
  interval: 1h
  url: oci://docker.io/envoyproxy
