---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: infra
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/infra/**"
          to: "@artifact/"
    - name: apps
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/apps/**"
          to: "@artifact/"
